grafana:
  adminPassword: "admin"
  defaultDashboardsEnabled: false
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.logging.svc.cluster.local:3100
      isDefault: false
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
    datasources:
      enabled: true

prometheus:
  prometheusSpec:
    retention: 15d
    scrapeInterval: 30s
    evaluationInterval: 30s
    ruleSelectorNilUsesHelmValues: false

alertmanager:
  config:
    route:
      receiver: "default"
      group_by: ["alertname","namespace","severity"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      routes:
        - matchers: [severity="critical"]
          receiver: "critical"
    receivers:
      - name: "default"
        webhook_configs:
          - url: "http://example-webhook.monitoring.svc.cluster.local:8080/"
      - name: "critical"
        email_configs:
          - to: "alerts@example.com"
            from: "noreply@example.com"
            smarthost: "smtp.example.com:587"
            auth_username: "noreply@example.com"
            auth_password: "REPLACE_ME"
  ingress:
    enabled: false
