apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service-api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "service-api.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "service-api.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "service-api.name" . }}
    spec:
      containers:
        - name: service-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
{{ toYaml .Values.resources | indent 12 }}
          env:
            - name: ENV
              valueFrom:
                fieldRef: { fieldPath: metadata.namespace }
