name: CD Prod
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Tag to deploy"
        required: true
concurrency:
  group: prod-${{ github.ref }}
  cancel-in-progress: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS creds via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          role-to-assume: ${{ secrets.AWS_GHA_ROLE_ARN_PROD }}
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region eu-central-1 --name e2e-prod-eks
      - name: Deploy via Helm
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          TAG="${{ inputs.image_tag }}"
          kubectl get ns apps >/dev/null 2>&1 || kubectl create ns apps
          helm upgrade --install service-api app/service-api/k8s/helm/service-api -n apps             --set image.repository="$ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/service-api"             --set image.tag="$TAG"
