apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://kps-kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
    isDefault: true
  - name: Loki
    type: loki
    access: proxy
    url: http://loki.logging.svc.cluster.local:3100
