image:
  repository: 000000000000.dkr.ecr.eu-central-1.amazonaws.com/service-api
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

ingress:
  enabled: false
  className: alb
  hosts:
    - host: demo.local
      paths:
        - path: /
          pathType: Prefix

metrics:
  enabled: true
  path: /metrics
  port: 8080
